version: '3'
services:
  autochannel-bot:
    image: hhollenstain/autochannel-bot:latest
    restart: always
    environment:
      APP_ID:
      AUTO_CATEGORIES:
      TOKEN:
      BLOCKED_USERS:
      GAMES:
      SQLALCHEMY_DATABASE_URI:
      ENV:
